# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3.0'

gem 'pdf-reader', '~> 2.0'
gem 'prawn', '~> 2.4'
gem 'prawn-table', '~> 0.2'
gem 'psych', '~> 5.0'

group :development do
  gem 'rubocop', '~> 1.50', require: false
  gem 'rubocop-performance', '~> 1.17', require: false
  gem 'rubocop-rspec', '~> 2.20', require: false
end

group :test do
  gem 'rspec', '~> 3.12'
  gem 'simplecov', '~> 0.22', require: false
end
